syntax on
set number
set relativenumber
set hlsearch
set incsearch
set ignorecase
set smartcase
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set ruler
set showcmd
set wildmenu
set scrolloff=5
set backspace=indent,eol,start
set mouse=a
set encoding=utf-8
